#! /bin/bash

#set -x

TRYCONFIG=$1
MAKEARGS=$*
if [ "$TRYCONFIG" = "debug" ]; then
	CONFIG=DEBUG
	shift
fi
if [ "$TRYCONFIG" = "gold" ]; then
	CONFIG=RELEASE
	shift
fi
if [ "$TRYCONFIG" = "release" ]; then
	CONFIG=RELWITHDEBINFO
	shift
fi
if [ "$TRYCONFIG" = "clean" ]; then
	shift
fi
if [ "$CONFIG" = "" ]; then
	CONFIG=DEBUG
fi

PROJECT=RenderSort
BUILDROOT=Build
BASE_DIR=`pwd`
BUILD_DIR=${BUILDROOT}/${PROJECT}_${CONFIG}
EXE_NAME=renderSort

cp ${PROJECT}.cmake CMakeLists.txt

mkdir -p ${BUILD_DIR}
pushd ${BUILD_DIR}
cmake -DCMAKE_BUILD_TYPE=${CONFIG} ${BASE_DIR} $*
make ${MAKEARGS}
if [ -e ${PROJECT}/a.out ]; then
	cp -v ${PROJECT}/a.out ${BASE_DIR}/${EXE_NAME}
fi
popd
ls -lh ${EXE_NAME}

