CMAKE_MINIMUM_REQUIRED(VERSION 2.6)

PROJECT(RENDERSORT)

#Global definitions
SET(GLOBAL_CFLAGS -Wall -Werror -Wdeclaration-after-statement)
SET(GLOBAL_DEFINITIONS ${GLOBAL_CFLAGS} ${CONFIG_CFLAGS})
SET(GLOBAL_INCLUDE_DIRECTORIES ${RENDERSORT_SOURCE_DIR}/LJ_Engine/LJ_LibDebug)
SET(GLOBAL_LINK_DIRECTORIES ${RENDERSORT_BINARY_DIR}/LJ_Engine/LJ_LibDebug)

#if you don't want the full compiler output, remove the following line
SET(CMAKE_VERBOSE_MAKEFILE OFF)

ADD_SUBDIRECTORY(LJ_Engine/LJ_LibDebug)
ADD_SUBDIRECTORY(RenderSort)
